project_id = "vdqcesikgxtdfdlgjcpd"

[functions.analyze-module]
verify_jwt = true

[functions.crawl-hotel-website]
verify_jwt = true

[functions.create-presentation]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.hotel-chat]
verify_jwt = true

[functions.init-admin]
verify_jwt = false
